//@version=5
indicator("Dashboard",overlay= true)
import vkpunique/PineHelper/5 as ph

//Replace this functions On next PineHelper Update 
method GetBGColorUp(float x,float badValue,float okValue,float normalValue)=>
    if x<badValue
        color.red
    else if x<okValue
        color.orange
    else if x<normalValue
        color(na)
    else
        color.green

//Sector and Industry Trend
GetSectorTrend(string sector)=>
	var sectorMap= map.new<string,int>()
	sectorMap.contains(sector)?sectorMap.get(sector):0

GetIndustryTrend(string industry)=>
	var industryMap= map.new<string,int>()
    industryMap.put("Agricultural Commodities/Milling",1)
    industryMap.put("Alternative Power Generation",1)
    industryMap.put("Building Products",1)
    industryMap.put("Chemicals: Agricultural",1)
    industryMap.put("Chemicals: Specialty",1)
    industryMap.put("Electronic Equipment/Instruments",1)
    industryMap.put("Finance/Rental/Leasing",1)
    industryMap.put("Financial Conglomerates",1)
    industryMap.put("Hospital/Nursing Management",1)
    industryMap.put("Household/Personal Care",1)
    industryMap.put("Investment Banks/Brokers",1)
    industryMap.put("Medical/Nursing Services",1)
    industryMap.put("Pharmaceuticals: Generic",1)
    industryMap.put("Pharmaceuticals: Major",1)
    industryMap.put("Pharmaceuticals: Other",1)
    industryMap.put("Steel",1)
    industryMap.put("Textiles",1)
	industryMap.contains(industry)?industryMap.get(industry):0

//General variables
[dailyOpen,dailyHigh,dailyLow,dailyClose] = request.security(syminfo.tickerid, "1D", [open,high,low,close])

//Market Cap Value
series float TSOFQ = request.financial(syminfo.tickerid, "TOTAL_SHARES_OUTSTANDING", "FQ",ignore_invalid_symbol=true)
series float TSOFY =request.financial(syminfo.tickerid, "TOTAL_SHARES_OUTSTANDING", "FY",ignore_invalid_symbol=true)
MarketCap = ph.IsStock()? (na(TSOFQ)?TSOFY:TSOFQ) * close:0

//Free Float Value
series float FSOFY =nz(request.financial(syminfo.tickerid, 'FLOAT_SHARES_OUTSTANDING', 'FY',ignore_invalid_symbol=true))
FreeFloat=ph.IsStock()? FSOFY*ta.vwap:0

////EMA Calculation
float ema10 = request.security(syminfo.tickerid, "1D",ta.ema(close, 10))
float ema21 = request.security(syminfo.tickerid, "1D",ta.ema(close, 21))
float ema50 = request.security(syminfo.tickerid, "1D",ta.ema(close, 50))

bool IsTrendingEMA=(ema10>ema21) and (ema21>ema50)
float ema10_Percentate=ph.Percentage(dailyClose,ema10)
float ema21_Percentate=ph.Percentage(dailyClose,ema21)
float ema50_Percentate=ph.Percentage(dailyClose,ema50)

////Ath Calculatoin
GetAllTimeHigh(dataSeries = high) =>
    highestHTF = request.security(syminfo.tickerid, "D", 
         ph.GetChartHighest(dataSeries)[1], lookahead=barmerge.lookahead_on)
    highestChartTF = ph.GetChartHighest(dataSeries)
    math.max(highestHTF, highestChartTF)

ath_Percentage=ph.Percentage(dailyClose,GetAllTimeHigh()[0])

//// ADR Calculation
adr_Percentage = (request.security(syminfo.tickerid, "1D",ta.sma(high/low, 20)) - 1)

//// Table Generation
show_dashboard = input(true, "Dashboard" )

int colId=0
if barstate.islast and show_dashboard
    var dashboard= table.new("top_center",10,2)
 
    ph.VerticleCell(dashboard,colId,"MCAP",ph.ToCrore(MarketCap), ph.GetBGColor(ph.RatioCrore(MarketCap),500,1000,10000,100000,200000))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId, "FF",ph.ToCrore(FreeFloat), ph.GetBGColor(ph.RatioCrore(FreeFloat),300,500,1000,10000,100000))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"EMA",IsTrendingEMA?"Pass":"Fail",ph.GetBGColor(IsTrendingEMA))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"EMA 10",ph.ToPercentage(ema10_Percentate),ph.GetBGColor(ema10_Percentate,-0.01,0,0.03,0.1,0.15))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"EMA 21",ph.ToPercentage(ema21_Percentate),ph.GetBGColor(ema10_Percentate,-0.01,0,0.03,0.1,0.15))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"EMA 50",ph.ToPercentage(ema50_Percentate),ph.GetBGColor(ema10_Percentate,-0.01,0,0.03,0.1,0.15))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"ATH",ph.ToPercentage(ath_Percentage),ph.GetBGColor(ath_Percentage,-0.2,-0.15,-0.1,-0.01,-0.005))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"ADR",ph.ToPercentage(adr_Percentage),GetBGColorUp(adr_Percentage,0,0.025,0.05))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"Sector",syminfo.sector,ph.GetBGColor3(GetSectorTrend(syminfo.sector) ))
    colId:=colId+1

    ph.VerticleCell(dashboard,colId,"Industry",syminfo.industry,ph.GetBGColor3(GetIndustryTrend(syminfo.industry)))
    colId:=colId+1
