//@version=5 
indicator(title="Main", overlay=true)

//Sector Map
var sectorMap= map.new<string,int>()
sectorMap.put("Commercial Services",0)
sectorMap.put("Communications",0)
sectorMap.put("Consumer Durables",0)
sectorMap.put("Consumer Non-Durables",0)
sectorMap.put("Consumer Services",0)
sectorMap.put("Distribution Services",0)
sectorMap.put("Electronic Technology",0)
sectorMap.put("Energy Minerals",0)
sectorMap.put("Finance",0)
sectorMap.put("Health Services",0)
sectorMap.put("Health Technology",1)
sectorMap.put("Industrial Services",0)
sectorMap.put("Miscellaneous",0)
sectorMap.put("Non-Energy Minerals",0)
sectorMap.put("Process Industries",0)
sectorMap.put("Producer Manufacturing",0)
sectorMap.put("Retail Trade",0)
sectorMap.put("Technology Services",1)
sectorMap.put("Transportation",0)
sectorMap.put("Utilities",1)

GetSectorTrend(x)=>sectorMap.contains(x)?sectorMap.get(x):0
GetSectorBGColor(int x)=> x>0?color.green:x<0?color.red:color(na)

//Industry Map
var industryMap= map.new<string,int>()
industryMap.put("Advertising/Marketing Services",0)
industryMap.put("Aerospace & Defense",0)
industryMap.put("Agricultural Commodities/Milling",0)
industryMap.put("Air Freight/Couriers",0)
industryMap.put("Airlines",0)
industryMap.put("Alternative Power Generation",0)
industryMap.put("Aluminum",0)
industryMap.put("Apparel/Footwear",0)
industryMap.put("Apparel/Footwear Retail",0)
industryMap.put("Auto Parts: OEM",0)
industryMap.put("Automotive Aftermarket",0)
industryMap.put("Beverages: Alcoholic",0)
industryMap.put("Beverages: Non-Alcoholic",0)
industryMap.put("Biotechnology",0)
industryMap.put("Broadcasting",0)
industryMap.put("Building Products",0)
industryMap.put("Cable/Satellite TV",0)
industryMap.put("Catalog/Specialty Distribution",0)
industryMap.put("Chemicals: Agricultural",0)
industryMap.put("Chemicals: Major Diversified",0)
industryMap.put("Chemicals: Specialty",0)
industryMap.put("Coal",0)
industryMap.put("Commercial Printing/Forms",0)
industryMap.put("Computer Communications",0)
industryMap.put("Computer Peripherals",0)
industryMap.put("Construction Materials",0)
industryMap.put("Consumer Sundries",0)
industryMap.put("Containers/Packaging",0)
industryMap.put("Contract Drilling",0)
industryMap.put("Data Processing Services",0)
industryMap.put("Department Stores",0)
industryMap.put("Drugstore Chains",0)
industryMap.put("Electric Utilities",0)
industryMap.put("Electrical Products",1)
industryMap.put("Electronic Components",0)
industryMap.put("Electronic Equipment/Instruments",0)
industryMap.put("Electronic Production Equipment",0)
industryMap.put("Electronics Distributors",0)
industryMap.put("Electronics/Appliance Stores",0)
industryMap.put("Electronics/Appliances",0)
industryMap.put("Engineering & Construction",0)
industryMap.put("Environmental Services",0)
industryMap.put("Finance/Rental/Leasing",0)
industryMap.put("Financial Conglomerates",0)
industryMap.put("Financial Publishing/Services",0)
industryMap.put("Food Distributors",0)
industryMap.put("Food Retail",0)
industryMap.put("Food: Major Diversified",0)
industryMap.put("Food: Meat/Fish/Dairy",0)
industryMap.put("Food: Specialty/Candy",0)
industryMap.put("Forest Products",0)
industryMap.put("Gas Distributors",0)
industryMap.put("Home Furnishings",0)
industryMap.put("Home Improvement Chains",0)
industryMap.put("Homebuilding",0)
industryMap.put("Hospital/Nursing Management",0)
industryMap.put("Hotels/Resorts/Cruise lines",0)
industryMap.put("Household/Personal Care",1)
industryMap.put("Industrial Conglomerates",0)
industryMap.put("Industrial Machinery",0)
industryMap.put("Industrial Specialties",0)
industryMap.put("Information Technology Services",1)
industryMap.put("Integrated Oil",0)
industryMap.put("Internet Retail",0)
industryMap.put("Internet Software/Services",0)
industryMap.put("Investment Banks/Brokers",0)
industryMap.put("Investment Managers",0)
industryMap.put("Investment Trusts/Mutual Funds",0)
industryMap.put("Life/Health Insurance",0)
industryMap.put("Major Banks",0)
industryMap.put("Major Telecommunications",0)
industryMap.put("Marine Shipping",0)
industryMap.put("Medical Distributors",0)
industryMap.put("Medical Specialties",0)
industryMap.put("Medical/Nursing Services",0)
industryMap.put("Metal Fabrication",0)
industryMap.put("Miscellaneous",0)
industryMap.put("Miscellaneous Commercial Services",0)
industryMap.put("Miscellaneous Manufacturing",0)
industryMap.put("Motor Vehicles",0)
industryMap.put("Movies/Entertainment",0)
industryMap.put("Multi-Line Insurance",0)
industryMap.put("Office Equipment/Supplies",0)
industryMap.put("Oil & Gas Pipelines",0)
industryMap.put("Oil & Gas Production",0)
industryMap.put("Oil Refining/Marketing",0)
industryMap.put("Oilfield Services/Equipment",0)
industryMap.put("Other Consumer Services",0)
industryMap.put("Other Consumer Specialties",0)
industryMap.put("Other Metals/Minerals",0)
industryMap.put("Other Transportation",0)
industryMap.put("Packaged Software",1)
industryMap.put("Personnel Services",0)
industryMap.put("Pharmaceuticals: Generic",1)
industryMap.put("Pharmaceuticals: Major",1)
industryMap.put("Pharmaceuticals: Other",1)
industryMap.put("Publishing: Books/Magazines",0)
industryMap.put("Publishing: Newspapers",0)
industryMap.put("Pulp & Paper",0)
industryMap.put("Railroads",0)
industryMap.put("Real Estate Development",0)
industryMap.put("Real Estate Investment Trusts",0)
industryMap.put("Recreational Products",0)
industryMap.put("Regional Banks",0)
industryMap.put("Restaurants",0)
industryMap.put("Semiconductors",0)
industryMap.put("Specialty Insurance",0)
industryMap.put("Specialty Stores",0)
industryMap.put("Specialty Telecommunications",0)
industryMap.put("Steel",0)
industryMap.put("Telecommunications Equipment",0)
industryMap.put("Textiles",0)
industryMap.put("Tobacco",0)
industryMap.put("Tools & Hardware",0)
industryMap.put("Trucking",0)
industryMap.put("Trucks/Construction/Farm Machinery",0)
industryMap.put("Wholesale Distributors",0)
industryMap.put("Wireless Telecommunications",0)


GetIndustryTrend(x)=>industryMap.contains(x)?industryMap.get(x):0

//Tolerance for Calculation Checks
float tolerance=input.float(0.1,"Tolerance %", minval=0.1, maxval=2, step=0.1)/100


//// Plot Moving Averages
show_10d = input(true, "10 Day")
plot(show_10d ? ta.ema(close, 10) : na, color = #ef2a57, title="10 Day")

show_21d = input(true , "21 Day" )
plot(show_21d ? ta.ema(close, 21 ) : na, color = #fc941a, title="21 Day")

show_50d = input(true , "50 Day" )
plot(show_50d ? ta.ema(close, 50 ) : na, color = #4eaf53, title="50 Day")

show_100d = input(false , "100 Day" )
plot(show_100d ? ta.ema(close, 100 ) : na, color = #3768fd, title="100 Day")

show_200d = input(false, "200 Day" )
plot(show_200d ? ta.ema(close, 200 ) : na, color = #fde947, title="200 Day")

plot(timeframe.isintraday ?  request.security(syminfo.tickerid, "1D",ta.ema(close, 10)) : na, color = #ef2a57,linewidth = 2, title="10 Day Fix")

//// Plot All time High

// GetChartHighest() returns the highest value of the given argument
// for the entire chart.
GetChartHighest(dataSeries = high) =>
    var chartHighest = dataSeries
    if dataSeries > nz(chartHighest, -1e10)
        chartHighest := dataSeries
    chartHighest

// GetAllTimeHigh() returns the all-time highest value for the given series
GetAllTimeHigh(dataSeries = high) =>
    highestHTF = request.security(syminfo.tickerid, "D", 
         GetChartHighest(dataSeries)[1], lookahead=barmerge.lookahead_on)
    highestChartTF = GetChartHighest(dataSeries)
    math.max(highestHTF, highestChartTF)

// Get and plot the all-time high
plot(series=GetAllTimeHigh(), color=color.white, linewidth=1,title="All-Time High")

//// Bull Snort
show_BullSnort = input(true, "BullSnort" ) and not timeframe.isintraday
if show_BullSnort
    vol = ta.sma(volume, 50)
    if  volume >= (vol*3) and close > close[1] and close > hlc3  == true
        label.new(bar_index, low, yloc= yloc.belowbar, color= color.white, style= label.style_circle , size = size.auto)

//// Inside bar
show_InsideBar=input(true,"InsideBar") and not timeframe.isintraday

data=high[1]*(1+tolerance)>=high and low[1]<=low*(1+tolerance) and show_InsideBar
plotshape(data, style=shape.diamond,location = location.belowbar, color= color.yellow, size = size.tiny, show_last=50)

//// Common Inputs
dailyClose=request.security(syminfo.tickerid,"1D",close)
dailyLow=request.security(syminfo.tickerid,"1D",low)
dailyHigh=request.security(syminfo.tickerid,"1D",high)

////EMA Calculation
ema10 = request.security(syminfo.tickerid, "1D",ta.ema(close, 10))
ema21 = request.security(syminfo.tickerid, "1D",ta.ema(close, 21))
ema50 = request.security(syminfo.tickerid, "1D",ta.ema(close, 50))

ema10_Percentate=(dailyClose-ema10)/ema10
ema21_Percentate=(dailyClose-ema21)/ema21
ema50_Percentate=(dailyClose-ema50)/ema50

GetEmaBGColor(x)=>x>=0.03?color(na):x>=0?color.green:color.red

string emaCheck=(ema10>ema21) and (ema21>ema50)?"Pass":"Fail"
GeEmaCheckBGColor(x)=>x=="Pass"?color(na):color.red

////Ath Calculatoin

float ath=GetAllTimeHigh()[0]
ath_Percentage=(dailyClose-ath)/ath
GetAthBGColor(x)=>x>=-0.05?color.green:x>=-0.15?color(na):x>=-0.2?color.orange:color.red
 
//// Table Generation
show_dashboard = input(true, "Dashboard" )

var rowId=0
var colId=0
var textColor=color.white

adr_Percentage = 100 * (request.security(syminfo.tickerid, "1D",ta.sma(high/low, 20)) - 1)
GetAdrBGColor(x)=>x>=5?color.green:x>=3.5?color(na):(x>=2.5?color.orange:color.red)

method Cells(table tbl,int rowId, int colId,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellText,text_color = textColor,bgcolor = backgroundcolor)

if barstate.islast and show_dashboard
    var dashboard= table.new("top_center",10,2)

    dashboard.Cells(rowId,colId,"EMA 10",color.black)
    dashboard.Cells(rowId+1,colId, str.tostring(ema10_Percentate,"0.00%"), GetEmaBGColor(ema10_Percentate))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"EMA 21",color.black)
    dashboard.Cells(rowId+1,colId, str.tostring(ema21_Percentate,"0.00%"), GetEmaBGColor(ema21_Percentate))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"EMA 50",color.black)
    dashboard.Cells(rowId+1,colId, str.tostring(ema50_Percentate,"0.00%"), GetEmaBGColor(ema50_Percentate))
    colId:=colId+1
 
    dashboard.Cells(rowId,colId,"ATH",color.black)
    dashboard.Cells(rowId+1,colId, str.tostring(ath_Percentage,"0.00%"), GetAthBGColor(ath_Percentage))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"ADR",color.black)  
    dashboard.Cells(rowId+1,colId, str.tostring(adr_Percentage,"0.00")+"%", GetAdrBGColor(adr_Percentage))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"EMA",color.black)
    dashboard.Cells(rowId+1,colId, emaCheck, GeEmaCheckBGColor(emaCheck))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"Sector",color.black)  
    dashboard.Cells(rowId+1,colId, syminfo.sector, GetSectorBGColor(GetSectorTrend(syminfo.sector)))
    colId:=colId+1

    dashboard.Cells(rowId,colId,"Industry",color.black)  
    dashboard.Cells(rowId+1,colId, syminfo.industry, GetSectorBGColor(GetIndustryTrend(syminfo.industry)))
    colId:=colId+1