// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © vkpunique

//@version=5

// @description TODO: add library description here
library("PineHelper", overlay=true)

//// Commanly Used fuctions for active Script™

//@function To check if current script is index or not
export method IsIndex(string symbolType=syminfo.type)=>
    symbolType=="index"

export method IsStock(string symbolType=syminfo.type)=>
    symbolType=="stock"

////Functions for value formatting

export method ToNoDecimal(float value)=>
    str.tostring(value,"0")

export method ToOneDecimal(float value)=>
    str.tostring(value,"0.0")

export method ToTwoDecimal(float value)=>
    str.tostring(value,"0.00")

export method ToPercentage(float value)=>
    str.tostring(value,"0.00%")

export method ToCrore(float value)=>
    value==0?"-":str.tostring(value/10000000,"0")+" Cr"

// @function Get Background Color Using 0,1 input
// @returns Color Type
export GetBGColor2(int value) =>
	switch value
		1=>color.green
		0=>color.red
		=>color(na)

// @function Get Background Color Using 0,1,-1 input
// @returns Color Type
export GetBGColor3(int value) =>
	switch value
		1=>color.green
		0=>color(na)
		-1=>color.red
		=>color(na)

//// Math/Chart Calculations

export Percentage(float currentValue, float baseValue)=>
	(currentValue-baseValue)/baseValue

export GetChartHighest(series float dataSeries = high) =>
    var chartHighest = dataSeries
    if dataSeries > nz(chartHighest, -1e10)
        chartHighest := dataSeries
    chartHighest

export GetEMA(int length)=>
	ta.ema(close,length)