//@version=6
library("PineHelper", overlay=true)

//Custom Types
export type Trade
    float BuyPrice
    string OrderDate

export type Sector
    int S1
    int S2
    int S3
    int S4

export enum StopLoss
    daylow ="DayLow"
    preDayLow  = "Pre DayLow"

export type Result
    string Name=""
    string Value=""
    color Color=na

export enum TableOrientation
    Horizontal
    Verticle

//// Commanly Used fuctions for active Script™

//@function To check if current script is index or not
export method IsIndex(string symbolType=syminfo.type)=>
    symbolType=="index"

export method IsStock(string symbolType=syminfo.type)=>
    symbolType=="stock"

////Functions for value formatting
export method ToNoDecimal(float value)=>
    str.tostring(value,"0")

export method ToOneDecimal(float value)=>
    str.tostring(value,"0.0")

export method ToTwoDecimal(float value)=>
    str.tostring(value,"0.00")

export method ToPercentage(float value)=>
    str.tostring(value,"0.00%")

export method ToThousand(float value)=>
    value==0?"-":str.tostring(value/1000,"0")+" K"

export method ToCrore(float value)=>
    value==0?"-":str.tostring(value/10000000,"0")+" Cr"

// @function Get Background Color Using 0,1 input
// @returns Color Type
export GetBGColor(int value) =>
	switch value
		1=>color.green
		0=>color.red
		=>na

// @function Get Background Color Using 0,1,-1 input
// @returns Color Type
export GetBGColor3(int value) =>
	switch value
		1=>color.green
		0=>na
		-1=>color.red
		=>na

export method GetBGColor(bool value) =>
	switch value
		true=>color.green
		false=>color.red
		=>na


export method GetBGColorUp(float x,float badValue,float okValue,float normalValue)=>
    if x<badValue
        color.red
    else if x<okValue
        color.orange    
	else if x<normalValue
        na
    else
        color.green

export method GetBGColorDown(float x,float badValue,float okValue,float normalValue)=>
    if x>badValue
        color.red
    else if x>okValue
        color.orange    
	else if x>normalValue
        na
    else
        color.green

export method GetBGColor(float x,float lowEnd,float lowEdge,float perfect,float normal, float highEdge)=>
    if x<lowEnd
        color.red
    else if x<lowEdge
        color.orange
    else if x<perfect
        color.green
    else if x<normal
        na
    else if x<highEdge
        color.orange
    else
        color.red

//// Math/Chart Calculations

export method RatioCrore(float value)=>
    value/10000000

export method Percentage(float currentValue, float baseValue)=>
	(currentValue-baseValue)/baseValue

export method GetChartHighest(series float dataSeries = high) =>
    var chartHighest = dataSeries
    if dataSeries > nz(chartHighest, -1e10)
        chartHighest := dataSeries
    chartHighest

export method GetEMA(int length)=>
	ta.ema(close,length)

//Table Util
export method HorizontalCell(table tbl, int rowId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,0,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,1,rowId,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method HorizontalCellBlank(table tbl, int rowId)=>
    table.cell(tbl,0,rowId,"",text_color = color.white,bgcolor = na)
    table.cell(tbl,1,rowId,"",text_color = color.white,bgcolor = na)

export method VerticleCell(table tbl, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,0,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,1,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method VerticleCellBlank(table tbl, int colId)=>
    table.cell(tbl,colId,0,"",text_color = color.white,bgcolor = na)
    table.cell(tbl,colId,1,"",text_color = color.white,bgcolor = na)

export method VerticleCell2(table tbl,int rowId, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,rowId+1,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method VerticleCell3(table tbl,int rowId, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,rowId+1,cellText,text_color = color.white,bgcolor = backgroundcolor)
    table.cell(tbl,colId,rowId+2,"",text_color = color.white,bgcolor = na)


export method GenerateTable(Result[] data,string position, TableOrientation orientation)=>
    Result firstItem= data.first()
    int numRows=orientation==TableOrientation.Verticle?data.size():2
    int numCols=orientation==TableOrientation.Verticle?2:data.size()
    var dashboard= table.new(position,numCols,numRows)
    if data.size()>0
        for i = 0 to  data.size() - 1
            Result item= data.get(i)
            if orientation==TableOrientation.Verticle
                table.cell(dashboard,0,i,item.Name,text_color = color.white,bgcolor = item.Name==""?na:color.black)
                table.cell(dashboard,1,i,item.Value,text_color = color.white,bgcolor = item.Color)
            else
                table.cell(dashboard,i,0,item.Name,text_color = color.white,bgcolor = item.Name==""?na:color.black)
                table.cell(dashboard,i,1,item.Value,text_color = color.white,bgcolor = item.Color)
    dashboard

export method AddResult(Result[] data,string name,string value, color backgroundColor=na)=>
    data.push(Result.new(name,value,backgroundColor))

export method AddResult(Result[] data)=>
    data.push(Result.new())

//Map Data Generators
export method GetMapDataInt(string data)=>
    var intMap= map.new<string,int>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==2
                ticker = parts.get(0)
                result = int(str.tonumber(parts.get(1)))
                intMap.put(ticker,result)
    intMap

export method GetMapDataFloat(string data)=>
    var floatMap= map.new<string,float>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==2
                ticker = parts.get(0)
                result = str.tonumber(parts.get(1))
                floatMap.put(ticker,result)
    floatMap
    
export method GetMapDataTrade(string data)=>
    var tradeMap= map.new<string,Trade>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==3 
                string ticker = parts.get(0)
                float price =str.tonumber(parts.get(1))
                string orderDate= parts.get(2)
                tradeMap.put(ticker,Trade.new(price,orderDate))
    tradeMap

export method GetMapDataSector(string data) =>
    var screenerMap = map.new<string, Sector>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==5 
                string ticker = parts.get(0)
                int s1 = int(str.tonumber(parts.get(1)))
                int s2 = int(str.tonumber(parts.get(2)))
                int s3 = int(str.tonumber(parts.get(3)))
                int s4 = int(str.tonumber(parts.get(4)))
                screenerMap.put(ticker,Sector.new(s1,s2,s3,s4))
    screenerMap

export method IsFNOStock(string symbol)=>
    var fnoMap= map.new<string,int>()
    fnoMap.put("360ONE",0)
    fnoMap.put("ABB",0)
    fnoMap.put("APLAPOLLO",0)
    fnoMap.put("AUBANK",0)
    fnoMap.put("ADANIENSOL",0)
    fnoMap.put("ADANIENT",0)
    fnoMap.put("ADANIGREEN",0)
    fnoMap.put("ADANIPORTS",0)
    fnoMap.put("ADANIPOWER",0)
    fnoMap.put("ABCAPITAL",0)
    fnoMap.put("ALKEM",0)
    fnoMap.put("AMBER",0)
    fnoMap.put("AMBUJACEM",0)
    fnoMap.put("ANGELONE",0)
    fnoMap.put("APOLLOHOSP",0)
    fnoMap.put("ASHOKLEY",0)
    fnoMap.put("ASIANPAINT",0)
    fnoMap.put("ASTRAL",0)
    fnoMap.put("AUROPHARMA",0)
    fnoMap.put("DMART",0)
    fnoMap.put("AXISBANK",0)
    fnoMap.put("BSE",0)
    fnoMap.put("BAJAJ-AUTO",0)
    fnoMap.put("BAJFINANCE",0)
    fnoMap.put("BAJAJFINSV",0)
    fnoMap.put("BAJAJHLDNG",0)
    fnoMap.put("BANDHANBNK",0)
    fnoMap.put("BANKBARODA",0)
    fnoMap.put("BANKINDIA",0)
    fnoMap.put("BDL",0)
    fnoMap.put("BEL",0)
    fnoMap.put("BHARATFORG",0)
    fnoMap.put("BHEL",0)
    fnoMap.put("BPCL",0)
    fnoMap.put("BHARTIARTL",0)
    fnoMap.put("BIOCON",0)
    fnoMap.put("BLUESTARCO",0)
    fnoMap.put("BOSCHLTD",0)
    fnoMap.put("BRITANNIA",0)
    fnoMap.put("CGPOWER",0)
    fnoMap.put("CANBK",0)
    fnoMap.put("CDSL",0)
    fnoMap.put("CHOLAFIN",0)
    fnoMap.put("CIPLA",0)
    fnoMap.put("COALINDIA",0)
    fnoMap.put("COCHINSHIP",0)
    fnoMap.put("COFORGE",0)
    fnoMap.put("COLPAL",0)
    fnoMap.put("CAMS",0)
    fnoMap.put("CONCOR",0)
    fnoMap.put("CROMPTON",0)
    fnoMap.put("CUMMINSIND",0)
    fnoMap.put("DLF",0)
    fnoMap.put("DABUR",0)
    fnoMap.put("DALBHARAT",0)
    fnoMap.put("DELHIVERY",0)
    fnoMap.put("DIVISLAB",0)
    fnoMap.put("DIXON",0)
    fnoMap.put("DRREDDY",0)
    fnoMap.put("ETERNAL",0)
    fnoMap.put("EICHERMOT",0)
    fnoMap.put("EXIDEIND",0)
    fnoMap.put("FORCEMOT",0)
    fnoMap.put("NYKAA",0)
    fnoMap.put("FORTIS",0)
    fnoMap.put("GAIL",0)
    fnoMap.put("GMRAIRPORT",0)
    fnoMap.put("GLENMARK",0)
    fnoMap.put("GODFRYPHLP",0)
    fnoMap.put("GODREJCP",0)
    fnoMap.put("GODREJPROP",0)
    fnoMap.put("GRASIM",0)
    fnoMap.put("HCLTECH",0)
    fnoMap.put("HDFCAMC",0)
    fnoMap.put("HDFCBANK",0)
    fnoMap.put("HDFCLIFE",0)
    fnoMap.put("HAVELLS",0)
    fnoMap.put("HEROMOTOCO",0)
    fnoMap.put("HINDALCO",0)
    fnoMap.put("HAL",0)
    fnoMap.put("HINDPETRO",0)
    fnoMap.put("HINDUNILVR",0)
    fnoMap.put("HINDZINC",0)
    fnoMap.put("POWERINDIA",0)
    fnoMap.put("HUDCO",0)
    fnoMap.put("HYUNDAI",0)
    fnoMap.put("ICICIBANK",0)
    fnoMap.put("ICICIGI",0)
    fnoMap.put("ICICIPRULI",0)
    fnoMap.put("IDFCFIRSTB",0)
    fnoMap.put("ITC",0)
    fnoMap.put("INDIANB",0)
    fnoMap.put("IEX",0)
    fnoMap.put("IOC",0)
    fnoMap.put("IRFC",0)
    fnoMap.put("IREDA",0)
    fnoMap.put("INDUSTOWER",0)
    fnoMap.put("INDUSINDBK",0)
    fnoMap.put("NAUKRI",0)
    fnoMap.put("INFY",0)
    fnoMap.put("INOXWIND",0)
    fnoMap.put("INDIGO",0)
    fnoMap.put("JINDALSTEL",0)
    fnoMap.put("JSWENERGY",0)
    fnoMap.put("JSWSTEEL",0)
    fnoMap.put("JIOFIN",0)
    fnoMap.put("JUBLFOOD",0)
    fnoMap.put("KEI",0)
    fnoMap.put("KPITTECH",0)
    fnoMap.put("KALYANKJIL",0)
    fnoMap.put("KAYNES",0)
    fnoMap.put("KFINTECH",0)
    fnoMap.put("KOTAKBANK",0)
    fnoMap.put("LTF",0)
    fnoMap.put("LICHSGFIN",0)
    fnoMap.put("LTM",0)
    fnoMap.put("LT",0)
    fnoMap.put("LAURUSLABS",0)
    fnoMap.put("LICI",0)
    fnoMap.put("LODHA",0)
    fnoMap.put("LUPIN",0)
    fnoMap.put("M&M",0)
    fnoMap.put("MANAPPURAM",0)
    fnoMap.put("MANKIND",0)
    fnoMap.put("MARICO",0)
    fnoMap.put("MARUTI",0)
    fnoMap.put("MFSL",0)
    fnoMap.put("MAXHEALTH",0)
    fnoMap.put("MAZDOCK",0)
    fnoMap.put("MOTILALOFS",0)
    fnoMap.put("MPHASIS",0)
    fnoMap.put("MCX",0)
    fnoMap.put("MUTHOOTFIN",0)
    fnoMap.put("NBCC",0)
    fnoMap.put("NHPC",0)
    fnoMap.put("NMDC",0)
    fnoMap.put("NTPC",0)
    fnoMap.put("NATIONALUM",0)
    fnoMap.put("NESTLEIND",0)
    fnoMap.put("NAM-INDIA",0)
    fnoMap.put("NUVAMA",0)
    fnoMap.put("OBEROIRLTY",0)
    fnoMap.put("ONGC",0)
    fnoMap.put("OIL",0)
    fnoMap.put("PAYTM",0)
    fnoMap.put("OFSS",0)
    fnoMap.put("POLICYBZR",0)
    fnoMap.put("PGEL",0)
    fnoMap.put("PIIND",0)
    fnoMap.put("PNBHOUSING",0)
    fnoMap.put("PAGEIND",0)
    fnoMap.put("PATANJALI",0)
    fnoMap.put("PERSISTENT",0)
    fnoMap.put("PETRONET",0)
    fnoMap.put("PIDILITIND",0)
    fnoMap.put("PPLPHARMA",0)
    fnoMap.put("POLYCAB",0)
    fnoMap.put("PFC",0)
    fnoMap.put("POWERGRID",0)
    fnoMap.put("PREMIERENE",0)
    fnoMap.put("PRESTIGE",0)
    fnoMap.put("PNB",0)
    fnoMap.put("RBLBANK",0)
    fnoMap.put("RECLTD",0)
    fnoMap.put("RVNL",0)
    fnoMap.put("RELIANCE",0)
    fnoMap.put("SBICARD",0)
    fnoMap.put("SBILIFE",0)
    fnoMap.put("SHREECEM",0)
    fnoMap.put("SRF",0)
    fnoMap.put("SAMMAANCAP",0)
    fnoMap.put("MOTHERSON",0)
    fnoMap.put("SHRIRAMFIN",0)
    fnoMap.put("SIEMENS",0)
    fnoMap.put("SOLARINDS",0)
    fnoMap.put("SONACOMS",0)
    fnoMap.put("SBIN",0)
    fnoMap.put("SAIL",0)
    fnoMap.put("SUNPHARMA",0)
    fnoMap.put("SUPREMEIND",0)
    fnoMap.put("SUZLON",0)
    fnoMap.put("SWIGGY",0)
    fnoMap.put("TATACONSUM",0)
    fnoMap.put("TVSMOTOR",0)
    fnoMap.put("TCS",0)
    fnoMap.put("TATAELXSI",0)
    fnoMap.put("TMPV",0)
    fnoMap.put("TATAPOWER",0)
    fnoMap.put("TATASTEEL",0)
    fnoMap.put("TATATECH",0)
    fnoMap.put("TECHM",0)
    fnoMap.put("FEDERALBNK",0)
    fnoMap.put("INDHOTEL",0)
    fnoMap.put("PHOENIXLTD",0)
    fnoMap.put("TITAN",0)
    fnoMap.put("TORNTPHARM",0)
    fnoMap.put("TORNTPOWER",0)
    fnoMap.put("TRENT",0)
    fnoMap.put("TIINDIA",0)
    fnoMap.put("UNOMINDA",0)
    fnoMap.put("UPL",0)
    fnoMap.put("ULTRACEMCO",0)
    fnoMap.put("UNIONBANK",0)
    fnoMap.put("UNITDSPR",0)
    fnoMap.put("VBL",0)
    fnoMap.put("VEDL",0)
    fnoMap.put("VMM",0)
    fnoMap.put("IDEA",0)
    fnoMap.put("VOLTAS",0)
    fnoMap.put("WAAREEENER",0)
    fnoMap.put("WIPRO",0)
    fnoMap.put("YESBANK",0)
    fnoMap.put("ZYDUSLIFE",0)
    fnoMap.contains(symbol)


export method GetS1(int id) =>
    var sMap = map.new<int, string>() 
    sMap.put(0,"-")
    sMap.put(1,"Commodities")
    sMap.put(2,"Consumer Discretionary")
    sMap.put(3,"Diversified")
    sMap.put(4,"Energy")
    sMap.put(5,"Fast Moving Consumer Goods")
    sMap.put(6,"Financial Services")
    sMap.put(7,"Healthcare")
    sMap.put(8,"Industrials")
    sMap.put(9,"Information Technology")
    sMap.put(10,"Services")
    sMap.put(11,"Telecommunication")
    sMap.put(12,"Utilities")
    sMap.get(id)

export method GetS2(int id) =>
    var sMap = map.new<int, string>() 
    sMap.put(0,"-")
    sMap.put(1,"Automobile and Auto Components")
    sMap.put(2,"Capital Goods")
    sMap.put(3,"Chemicals")
    sMap.put(4,"Construction")
    sMap.put(5,"Construction Materials")
    sMap.put(6,"Consumer Durables")
    sMap.put(7,"Consumer Services")
    sMap.put(8,"Diversified")
    sMap.put(9,"Fast Moving Consumer Goods")
    sMap.put(10,"Financial Services")
    sMap.put(11,"Forest Materials")
    sMap.put(12,"Healthcare")
    sMap.put(13,"Information Technology")
    sMap.put(14,"Media, Entertainment & Publication")
    sMap.put(15,"Metals & Mining")
    sMap.put(16,"Oil, Gas & Consumable Fuels")
    sMap.put(17,"Power")
    sMap.put(18,"Realty")
    sMap.put(19,"Services")
    sMap.put(20,"Telecommunication")
    sMap.put(21,"Textiles")
    sMap.put(22,"Utilities")
    sMap.get(id)

export method GetS3(int id) =>
    var sMap = map.new<int, string>() 
    sMap.put(0,"-")
    sMap.put(1,"Aerospace & Defense")
    sMap.put(2,"Agricultural Food & other Products")
    sMap.put(3,"Agricultural, Commercial & Construction Vehicles")
    sMap.put(4,"Auto Components")
    sMap.put(5,"Automobiles")
    sMap.put(6,"Banks")
    sMap.put(7,"Beverages")
    sMap.put(8,"Capital Markets")
    sMap.put(9,"Cement & Cement Products")
    sMap.put(10,"Chemicals & Petrochemicals")
    sMap.put(11,"Cigarettes & Tobacco Products")
    sMap.put(12,"Commercial Services & Supplies")
    sMap.put(13,"Construction")
    sMap.put(14,"Consumable Fuels")
    sMap.put(15,"Consumer Durables")
    sMap.put(16,"Diversified")
    sMap.put(17,"Diversified FMCG")
    sMap.put(18,"Diversified Metals")
    sMap.put(19,"Electrical Equipment")
    sMap.put(20,"Engineering Services")
    sMap.put(21,"Entertainment")
    sMap.put(22,"Ferrous Metals")
    sMap.put(23,"Fertilizers & Agrochemicals")
    sMap.put(24,"Finance")
    sMap.put(25,"Financial Technology (Fintech)")
    sMap.put(26,"Food Products")
    sMap.put(27,"Gas")
    sMap.put(28,"Healthcare Equipment & Supplies")
    sMap.put(29,"Healthcare Services")
    sMap.put(30,"Household Products")
    sMap.put(31,"Industrial Manufacturing")
    sMap.put(32,"Industrial Products")
    sMap.put(33,"Insurance")
    sMap.put(34,"IT - Hardware")
    sMap.put(35,"IT - Services")
    sMap.put(36,"IT - Software")
    sMap.put(37,"Leisure Services")
    sMap.put(38,"Media")
    sMap.put(39,"Metals & Minerals Trading")
    sMap.put(40,"Minerals & Mining")
    sMap.put(41,"Non - Ferrous Metals")
    sMap.put(42,"Oil")
    sMap.put(43,"Other Construction Materials")
    sMap.put(44,"Other Consumer Services")
    sMap.put(45,"Other Utilities")
    sMap.put(46,"Paper, Forest & Jute Products")
    sMap.put(47,"Personal Products")
    sMap.put(48,"Petroleum Products")
    sMap.put(49,"Pharmaceuticals & Biotechnology")
    sMap.put(50,"Power")
    sMap.put(51,"Printing & Publication")
    sMap.put(52,"Realty")
    sMap.put(53,"Retailing")
    sMap.put(54,"Telecom - Equipment & Accessories")
    sMap.put(55,"Telecom - Services")
    sMap.put(56,"Textiles & Apparels")
    sMap.put(57,"Transport Infrastructure")
    sMap.put(58,"Transport Services")
    sMap.get(id)

export method GetS4(int id) =>
    var sMap = map.new<int, string>() 
    sMap.put(0,"-")
    sMap.put(1,"2/3 Wheelers")
    sMap.put(2,"Abrasives & Bearings")
    sMap.put(3,"Advertising & Media Agencies")
    sMap.put(4,"Aerospace & Defense")
    sMap.put(5,"Airline")
    sMap.put(6,"Airport & Airport services")
    sMap.put(7,"Aluminium")
    sMap.put(8,"Aluminium, Copper & Zinc Products")
    sMap.put(9,"Amusement Parks/ Other Recreation")
    sMap.put(10,"Animal Feed")
    sMap.put(11,"Asset Management Company")
    sMap.put(12,"Auto Components & Equipments")
    sMap.put(13,"Auto Dealer")
    sMap.put(14,"Biotechnology")
    sMap.put(15,"Breweries & Distilleries")
    sMap.put(16,"Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)")
    sMap.put(17,"Cables - Electricals")
    sMap.put(18,"Carbon Black")
    sMap.put(19,"Castings & Forgings")
    sMap.put(20,"Cement & Cement Products")
    sMap.put(21,"Ceramics")
    sMap.put(22,"Cigarettes & Tobacco Products")
    sMap.put(23,"Civil Construction")
    sMap.put(24,"Coal")
    sMap.put(25,"Commercial Vehicles")
    sMap.put(26,"Commodity Chemicals")
    sMap.put(27,"Compressors, Pumps & Diesel Engines")
    sMap.put(28,"Computers - Software & Consulting")
    sMap.put(29,"Computers Hardware & Equipments")
    sMap.put(30,"Construction Vehicles")
    sMap.put(31,"Consulting Services")
    sMap.put(32,"Consumer Electronics")
    sMap.put(33,"Copper")
    sMap.put(34,"Cycles")
    sMap.put(35,"Dairy Products")
    sMap.put(36,"Data Processing Services")
    sMap.put(37,"Dealers-Commercial Vehicles, Tractors, Construction Vehicles")
    sMap.put(38,"Depositories, Clearing Houses and Other Intermediaries")
    sMap.put(39,"Digital Entertainment")
    sMap.put(40,"Diversified")
    sMap.put(41,"Diversified Commercial Services")
    sMap.put(42,"Diversified FMCG")
    sMap.put(43,"Diversified Metals")
    sMap.put(44,"Diversified Retail")
    sMap.put(45,"Dredging")
    sMap.put(46,"Dyes And Pigments")
    sMap.put(47,"Edible Oil")
    sMap.put(48,"Education")
    sMap.put(49,"E-Learning")
    sMap.put(50,"Electrodes & Refractories")
    sMap.put(51,"Electronic Media")
    sMap.put(52,"E-Retail/ E-Commerce")
    sMap.put(53,"Exchange and Data Platform")
    sMap.put(54,"Explosives")
    sMap.put(55,"Ferro & Silica Manganese")
    sMap.put(56,"Fertilizers")
    sMap.put(57,"Film Production, Distribution & Exhibition")
    sMap.put(58,"Financial Institution")
    sMap.put(59,"Financial Products Distributor")
    sMap.put(60,"Financial Technology (Fintech)")
    sMap.put(61,"Footwear")
    sMap.put(62,"Furniture, Home Furnishing")
    sMap.put(63,"Garments & Apparels")
    sMap.put(64,"Gas Transmission/Marketing")
    sMap.put(65,"Gems, Jewellery And Watches")
    sMap.put(66,"General Insurance")
    sMap.put(67,"Glass - Consumer")
    sMap.put(68,"Glass - Industrial")
    sMap.put(69,"Granites & Marbles")
    sMap.put(70,"Healthcare Research, Analytics & Technology")
    sMap.put(71,"Healthcare Service Provider")
    sMap.put(72,"Heavy Electrical Equipment")
    sMap.put(73,"Holding Company")
    sMap.put(74,"Hospital")
    sMap.put(75,"Hotels & Resorts")
    sMap.put(76,"Household Appliances")
    sMap.put(77,"Household Products")
    sMap.put(78,"Houseware")
    sMap.put(79,"Housing Finance Company")
    sMap.put(80,"Industrial Gases")
    sMap.put(81,"Industrial Minerals")
    sMap.put(82,"Industrial Products")
    sMap.put(83,"Insurance Distributors")
    sMap.put(84,"Integrated Power Utilities")
    sMap.put(85,"Internet & Catalogue Retail")
    sMap.put(86,"Investment Company")
    sMap.put(87,"Iron & Steel")
    sMap.put(88,"Iron & Steel Products")
    sMap.put(89,"IT Enabled Services")
    sMap.put(90,"Jute & Jute Products")
    sMap.put(91,"Leather And Leather Products")
    sMap.put(92,"Leisure Products")
    sMap.put(93,"Life Insurance")
    sMap.put(94,"Logistics Solution Provider")
    sMap.put(95,"LPG/CNG/PNG/LNG Supplier")
    sMap.put(96,"Lubricants")
    sMap.put(97,"Meat Products including Poultry")
    sMap.put(98,"Media & Entertainment")
    sMap.put(99,"Medical Equipment & Supplies")
    sMap.put(100,"Microfinance Institutions")
    sMap.put(101,"Non Banking Financial Company (NBFC)")
    sMap.put(102,"Offshore Support Solution Drilling")
    sMap.put(103,"Oil Equipment & Services")
    sMap.put(104,"Oil Exploration & Production")
    sMap.put(105,"Oil Storage & Transportation")
    sMap.put(106,"Other Agricultural Products")
    sMap.put(107,"Other Bank")
    sMap.put(108,"Other Beverages")
    sMap.put(109,"Other Capital Market related Services")
    sMap.put(110,"Other Construction Materials")
    sMap.put(111,"Other Consumer Services")
    sMap.put(112,"Other Electrical Equipment")
    sMap.put(113,"Other Financial Services")
    sMap.put(114,"Other Food Products")
    sMap.put(115,"Other Industrial Products")
    sMap.put(116,"Other Telecom Services")
    sMap.put(117,"Other Textile Products")
    sMap.put(118,"Packaged Foods")
    sMap.put(119,"Packaging")
    sMap.put(120,"Paints")
    sMap.put(121,"Paper & Paper Products")
    sMap.put(122,"Passenger Cars & Utility Vehicles")
    sMap.put(123,"Personal Care")
    sMap.put(124,"Pesticides & Agrochemicals")
    sMap.put(125,"Petrochemicals")
    sMap.put(126,"Pharmaceuticals")
    sMap.put(127,"Pharmacy Retail")
    sMap.put(128,"Plastic Products - Consumer")
    sMap.put(129,"Plastic Products - Industrial")
    sMap.put(130,"Plywood Boards/ Laminates")
    sMap.put(131,"Port & Port services")
    sMap.put(132,"Power - Transmission")
    sMap.put(133,"Power Distribution")
    sMap.put(134,"Power Generation")
    sMap.put(135,"Power Trading")
    sMap.put(136,"Print Media")
    sMap.put(137,"Printing & Publication")
    sMap.put(138,"Printing Inks")
    sMap.put(139,"Private Sector Bank")
    sMap.put(140,"Public Sector Bank")
    sMap.put(141,"Railway Wagons")
    sMap.put(142,"Ratings")
    sMap.put(143,"Real Estate related services")
    sMap.put(144,"Refineries & Marketing")
    sMap.put(145,"Residential, Commercial Projects")
    sMap.put(146,"Restaurants")
    sMap.put(147,"Road AssetsToll, Annuity, Hybrid-Annuity")
    sMap.put(148,"Road Transport")
    sMap.put(149,"Rubber")
    sMap.put(150,"Sanitary Ware")
    sMap.put(151,"Seafood")
    sMap.put(152,"Ship Building & Allied Services")
    sMap.put(153,"Shipping")
    sMap.put(154,"Software Products")
    sMap.put(155,"Speciality Retail")
    sMap.put(156,"Specialty Chemicals")
    sMap.put(157,"Sponge Iron")
    sMap.put(158,"Stationary")
    sMap.put(159,"Stockbroking & Allied")
    sMap.put(160,"Sugar")
    sMap.put(161,"Tea & Coffee")
    sMap.put(162,"Telecom - Cellular & Fixed line services")
    sMap.put(163,"Telecom - Equipment & Accessories")
    sMap.put(164,"Telecom - Infrastructure")
    sMap.put(165,"Tour, Travel Related Services")
    sMap.put(166,"Tractors")
    sMap.put(167,"Trading - Auto components")
    sMap.put(168,"Trading - Chemicals")
    sMap.put(169,"Trading - Coal")
    sMap.put(170,"Trading - Gas")
    sMap.put(171,"Trading - Metals")
    sMap.put(172,"Trading - Minerals")
    sMap.put(173,"Trading - Textile Products")
    sMap.put(174,"Trading & Distributors")
    sMap.put(175,"Transport Related Services")
    sMap.put(176,"TV Broadcasting & Software Production")
    sMap.put(177,"Tyres & Rubber Products")
    sMap.put(178,"Waste Management")
    sMap.put(179,"Water Supply & Management")
    sMap.put(180,"Web based media and service")
    sMap.put(181,"Wellness")
    sMap.put(182,"Zinc")
    sMap.get(id)