//@version=5
library("PineHelper", overlay=true)

//Custom Types
export type Trade
    float BuyPrice
    string OrderDate

export enum StopLoss
    daylow ="DayLow"
    preDayLow  = "Pre DayLow"

export type Result
    string Name=""
    string Value=""
    color Color=na

export enum TableOrientation
    Horizontal
    Verticle

//// Commanly Used fuctions for active Script™

//@function To check if current script is index or not
export method IsIndex(string symbolType=syminfo.type)=>
    symbolType=="index"

export method IsStock(string symbolType=syminfo.type)=>
    symbolType=="stock"

////Functions for value formatting

export method ToNoDecimal(float value)=>
    str.tostring(value,"0")

export method ToOneDecimal(float value)=>
    str.tostring(value,"0.0")

export method ToTwoDecimal(float value)=>
    str.tostring(value,"0.00")

export method ToPercentage(float value)=>
    str.tostring(value,"0.00%")

export method ToThousand(float value)=>
    value==0?"-":str.tostring(value/1000,"0")+" K"

export method ToCrore(float value)=>
    value==0?"-":str.tostring(value/10000000,"0")+" Cr"

// @function Get Background Color Using 0,1 input
// @returns Color Type
export GetBGColor(int value) =>
	switch value
		1=>color.green
		0=>color.red
		=>color(na)

// @function Get Background Color Using 0,1,-1 input
// @returns Color Type
export GetBGColor3(int value) =>
	switch value
		1=>color.green
		0=>color(na)
		-1=>color.red
		=>color(na)

export method GetBGColor(bool value) =>
	switch value
		true=>color.green
		false=>color.red
		=>color(na)


export method GetBGColorUp(float x,float badValue,float okValue,float normalValue)=>
    if x<badValue
        color.red
    else if x<okValue
        color.orange    
	else if x<normalValue
        color(na)
    else
        color.green

export method GetBGColorDown(float x,float badValue,float okValue,float normalValue)=>
    if x>badValue
        color.red
    else if x>okValue
        color.orange    
	else if x>normalValue
        color(na)
    else
        color.green

export method GetBGColor(float x,float lowEnd,float lowEdge,float perfect,float normal, float highEdge)=>
    if x<lowEnd
        color.red
    else if x<lowEdge
        color.orange
    else if x<perfect
        color.green
    else if x<normal
        color(na)
    else if x<highEdge
        color.orange
    else
        color.red

//// Math/Chart Calculations

export method RatioCrore(float value)=>
    value/10000000

export method Percentage(float currentValue, float baseValue)=>
	(currentValue-baseValue)/baseValue

export method GetChartHighest(series float dataSeries = high) =>
    var chartHighest = dataSeries
    if dataSeries > nz(chartHighest, -1e10)
        chartHighest := dataSeries
    chartHighest

export method GetEMA(int length)=>
	ta.ema(close,length)

//Table Util

export method HorizontalCell(table tbl, int rowId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,0,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,1,rowId,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method HorizontalCellBlank(table tbl, int rowId)=>
    table.cell(tbl,0,rowId,"",text_color = color.white,bgcolor = color(na))
    table.cell(tbl,1,rowId,"",text_color = color.white,bgcolor = color(na))

export method VerticleCell(table tbl, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,0,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,1,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method VerticleCellBlank(table tbl, int colId)=>
    table.cell(tbl,colId,0,"",text_color = color.white,bgcolor = color(na))
    table.cell(tbl,colId,1,"",text_color = color.white,bgcolor = color(na))

export method VerticleCell2(table tbl,int rowId, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,rowId+1,cellText,text_color = color.white,bgcolor = backgroundcolor)

export method VerticleCell3(table tbl,int rowId, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,rowId+1,cellText,text_color = color.white,bgcolor = backgroundcolor)
    table.cell(tbl,colId,rowId+2,"",text_color = color.white,bgcolor = color(na))


export method GenerateTable(Result[] data,string position, TableOrientation orientation)=>
    Result firstItem= data.first()
    int numRows=orientation==TableOrientation.Verticle?data.size():2
    int numCols=orientation==TableOrientation.Verticle?2:data.size()
    var dashboard= table.new(position,numCols,numRows)
    if data.size()>0
        for i = 0 to  data.size() - 1
            Result item= data.get(i)
            if orientation==TableOrientation.Verticle
                table.cell(dashboard,0,i,item.Name,text_color = color.white,bgcolor = item.Name==""?na:color.black)
                table.cell(dashboard,1,i,item.Value,text_color = color.white,bgcolor = item.Color)
            else
                table.cell(dashboard,i,0,item.Name,text_color = color.white,bgcolor = item.Name==""?na:color.black)
                table.cell(dashboard,i,1,item.Value,text_color = color.white,bgcolor = item.Color)
    dashboard

export method AddResult(Result[] data,string name,string value, color backgroundColor=na)=>
    data.push(Result.new(name,value,backgroundColor))

export method AddResult(Result[] data)=>
    data.push(Result.new())

//Map Data Generators
export method GetMapDataFloat(string data)=>
    var floatMap= map.new<string,float>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==2
                ticker = parts.get(0)
                result = str.tonumber(parts.get(1))
                floatMap.put(ticker,result)
    floatMap
    
export method GetMapDataTrade(string data)=>
    var tradeMap= map.new<string,Trade>()
    if data !=""
        lines = str.split(data, "\n")
        for i = 0 to array.size(lines) - 1
            line = array.get(lines, i)
            parts= str.split(line,",")
            if parts.size()==3 
                string ticker = parts.get(0)
                float price =str.tonumber(parts.get(1))
                string orderDate= parts.get(2)
                tradeMap.put(ticker,Trade.new(price,orderDate))
    tradeMap

export method IsFNOStock(string symbol)=>
    var fnoMap= map.new<string,int>()
    fnoMap.put("INDIGO",0)
    fnoMap.put("BAJAJ-AUTO",0)
    fnoMap.put("DIXON",0)
    fnoMap.put("TVSMOTOR",0)
    fnoMap.put("MCX",0)
    fnoMap.put("PEL",0)
    fnoMap.put("TATAMOTORS",0)
    fnoMap.put("COALINDIA",0)
    fnoMap.put("HEROMOTOCO",0)
    fnoMap.put("GMRINFRA",0)
    fnoMap.put("BPCL",0)
    fnoMap.put("HAL",0)
    fnoMap.put("AMBUJACEM",0)
    fnoMap.put("MOTHERSON",0)
    fnoMap.put("M&M",0)
    fnoMap.put("ICICIPRULI",0)
    fnoMap.put("ESCORTS",0)
    fnoMap.put("SUNPHARMA",0)
    fnoMap.put("MFSL",0)
    fnoMap.put("HINDPETRO",0)
    fnoMap.put("BEL",0)
    fnoMap.put("APOLLOHOSP",0)
    fnoMap.put("ICICIBANK",0)
    fnoMap.put("ICICIGI",0)
    fnoMap.put("BHARTIARTL",0)
    fnoMap.put("CONCOR",0)
    fnoMap.put("IOC",0)
    fnoMap.put("MANAPPURAM",0)
    fnoMap.put("POWERGRID",0)
    fnoMap.put("SBICARD",0)
    fnoMap.put("HINDUNILVR",0)
    fnoMap.put("INDUSTOWER",0)
    fnoMap.put("JSWSTEEL",0)
    fnoMap.put("BAJAJFINSV",0)
    fnoMap.put("RELIANCE",0)
    fnoMap.put("SYNGENE",0)
    fnoMap.put("CANBK",0)
    fnoMap.put("CUMMINSIND",0)
    fnoMap.put("HDFCLIFE",0)
    fnoMap.put("MARUTI",0)
    fnoMap.put("CANFINHOME",0)
    fnoMap.put("VOLTAS",0)
    fnoMap.put("KOTAKBANK",0)
    fnoMap.put("NTPC",0)
    fnoMap.put("AUROPHARMA",0)
    fnoMap.put("SAIL",0)
    fnoMap.put("NIFTY",0)
    fnoMap.put("EICHERMOT",0)
    fnoMap.put("SBILIFE",0)
    fnoMap.put("BHARATFORG",0)
    fnoMap.put("AXISBANK",0)
    fnoMap.put("JKCEMENT",0)
    fnoMap.put("BALKRISIND",0)
    fnoMap.put("TATACOMM",0)
    fnoMap.put("LTTS",0)
    fnoMap.put("BANKNIFTY",0)
    fnoMap.put("TRENT",0)
    fnoMap.put("BAJFINANCE",0)
    fnoMap.put("ALKEM",0)
    fnoMap.put("BHEL",0)
    fnoMap.put("GUJGASLTD",0)
    fnoMap.put("ITC",0)
    fnoMap.put("SIEMENS",0)
    fnoMap.put("DALBHARAT",0)
    fnoMap.put("JINDALSTEL",0)
    fnoMap.put("ASHOKLEY",0)
    fnoMap.put("ADANIPORTS",0)
    fnoMap.put("INDUSINDBK",0)
    fnoMap.put("CROMPTON",0)
    fnoMap.put("NATIONALUM",0)
    fnoMap.put("BRITANNIA",0)
    fnoMap.put("ULTRACEMCO",0)
    fnoMap.put("HDFCAMC",0)
    fnoMap.put("HDFCBANK",0)
    fnoMap.put("DRREDDY",0)
    fnoMap.put("APOLLOTYRE",0)
    fnoMap.put("TATASTEEL",0)
    fnoMap.put("POLYCAB",0)
    fnoMap.put("BATAINDIA",0)
    fnoMap.put("BANKBARODA",0)
    fnoMap.put("PNB",0)
    fnoMap.put("ASTRAL",0)
    fnoMap.put("LT",0)
    fnoMap.put("GRANULES",0)
    fnoMap.put("GNFC",0)
    fnoMap.put("ABFRL",0)
    fnoMap.put("ABB",0)
    fnoMap.put("INDIAMART",0)
    fnoMap.put("SBIN",0)
    fnoMap.put("DABUR",0)
    fnoMap.put("GLENMARK",0)
    fnoMap.put("PFC",0)
    fnoMap.put("TORNTPHARM",0)
    fnoMap.put("GRASIM",0)
    fnoMap.put("IDFC",0)
    fnoMap.put("NESTLEIND",0)
    fnoMap.put("TATACONSUM",0)
    fnoMap.put("HCLTECH",0)
    fnoMap.put("BSOFT",0)
    fnoMap.put("UPL",0)
    fnoMap.put("SHRIRAMFIN",0)
    fnoMap.put("INDIACEM",0)
    fnoMap.put("LALPATHLAB",0)
    fnoMap.put("LTF",0)
    fnoMap.put("INDHOTEL",0)
    fnoMap.put("LUPIN",0)
    fnoMap.put("INFY",0)
    fnoMap.put("LAURUSLABS",0)
    fnoMap.put("PIIND",0)
    fnoMap.put("MRF",0)
    fnoMap.put("PAGEIND",0)
    fnoMap.put("BOSCHLTD",0)
    fnoMap.put("CHOLAFIN",0)
    fnoMap.put("AUBANK",0)
    fnoMap.put("ABCAPITAL",0)
    fnoMap.put("IDFCFIRSTB",0)
    fnoMap.put("HAVELLS",0)
    fnoMap.put("AARTIIND",0)
    fnoMap.put("GODREJCP",0)
    fnoMap.put("CIPLA",0)
    fnoMap.put("HINDALCO",0)
    fnoMap.put("ADANIENT",0)
    fnoMap.put("ASIANPAINT",0)
    fnoMap.put("DLF",0)
    fnoMap.put("CUB",0)
    fnoMap.put("RAMCOCEM",0)
    fnoMap.put("COFORGE",0)
    fnoMap.put("TCS",0)
    fnoMap.put("ACC",0)
    fnoMap.put("TITAN",0)
    fnoMap.put("TATAPOWER",0)
    fnoMap.put("TECHM",0)
    fnoMap.put("IRCTC",0)
    fnoMap.put("JUBLFOOD",0)
    fnoMap.put("BANDHANBNK",0)
    fnoMap.put("ABBOTINDIA",0)
    fnoMap.put("RECLTD",0)
    fnoMap.put("MARICO",0)
    fnoMap.put("IDEA",0)
    fnoMap.put("NAUKRI",0)
    fnoMap.put("UBL",0)
    fnoMap.put("PIDILITIND",0)
    fnoMap.put("BIOCON",0)
    fnoMap.put("LTIM",0)
    fnoMap.put("MUTHOOTFIN",0)
    fnoMap.put("SHREECEM",0)
    fnoMap.put("WIPRO",0)
    fnoMap.put("NMDC",0)
    fnoMap.put("M&MFIN",0)
    fnoMap.put("PERSISTENT",0)
    fnoMap.put("HINDCOPPER",0)
    fnoMap.put("LICHSGFIN",0)
    fnoMap.put("RBLBANK",0)
    fnoMap.put("GAIL",0)
    fnoMap.put("ONGC",0)
    fnoMap.put("NAVINFLUOR",0)
    fnoMap.put("TATACHEM",0)
    fnoMap.put("ATUL",0)
    fnoMap.put("PVRINOX",0)
    fnoMap.put("COLPAL",0)
    fnoMap.put("OFSS",0)
    fnoMap.put("SUNTV",0)
    fnoMap.put("DIVISLAB",0)
    fnoMap.put("METROPOLIS",0)
    fnoMap.put("UNITDSPR",0)
    fnoMap.put("IPCALAB",0)
    fnoMap.put("COROMANDEL",0)
    fnoMap.put("SRF",0)
    fnoMap.put("FEDERALBNK",0)
    fnoMap.put("EXIDEIND",0)
    fnoMap.put("ZYDUSLIFE",0)
    fnoMap.put("PETRONET",0)
    fnoMap.put("OBEROIRLTY",0)
    fnoMap.put("GODREJPROP",0)
    fnoMap.put("VEDL",0)
    fnoMap.put("BERGEPAINT",0)
    fnoMap.put("MPHASIS",0)
    fnoMap.put("MGL",0)
    fnoMap.put("IGL",0)
    fnoMap.put("CHAMBLFERT",0)
    fnoMap.put("IEX",0)
    fnoMap.put("DEEPAKNTR",0)
    fnoMap.put("BALRAMCHIN",0)
    fnoMap.contains(symbol)