title: Home
nav:
  - Home:
    - index.md
    - "*"
  - Trading Process: 
    - index.md
    - *
    - Personal Indicators:
      - *
  - Concepts: Concepts
  - Chart Patterns: Chart Patterns
  - Pine Script: Pine Script
  - Trading View: Trading View
  - Momentum Investing: Momentum Investing